# This is the network config written by 'subiquity'
network:
  ethernets:
    enp0s3:
      dhcp4: no
      dhcp6: no
      addresses: [192.168.4.101/24]
      routes:
        - to: default
          via: 192.168.4.110
      nameservers:
        addresses: [8.8.8.8, 8.8.8.4]
  version: 2
